/*
 * This source file was generated by the Gradle 'init' task
 */
package org.scrollSystem;

import org.scrollSystem.utility.EnvLoader;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.Map;

@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello World";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // Load the .env file manually
        Map<String, String> envVars = EnvLoader.loadEnv(".env");
        // Set System properties (will be picked up by Spring Boot)
        envVars.forEach(System::setProperty);

        SpringApplication.run(App.class, args);

    }

}
